In [1]:
import pandas as pd

In [41]:
pd.__version__

'0.22.0'

In [56]:
dfs = pd.read_excel('2017 Matriculant Satisfaction Survey_June 4, 2018_10.54_Edited.xlsx', keep_default_na= False)

In [7]:
dfs1 = pd.read_excel('2017 Matriculant Satisfaction Survey_June 4, 2018_10.54_Edited2.xlsx')

In [44]:
dfs[['D4_6_TEXT']].head()

         D4_6_TEXT
0
1
2
3  Caucasian/Asian
4

In [34]:
dfs[['OTD1']].head()

     OTD1
0  #NULL!
1  #NULL!
2  #NULL!
3  #NULL!
4  #NULL!

In [57]:
dfs = dfs.fillna('#NULL!')

In [46]:
dfs.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration__in_seconds_,Finished,RecordedDate,ResponseId,RecipientLastName,...,JCHP2_4,JCHP3,OTD1,OTD2,OTD3,OTD4,OTD5,JCN1,JCN2,filter_$
0,2018-05-08 10:32:15,2018-05-08 10:51:19,IP Address,170.212.0.96,100,1143,True,2018-05-08 10:51:19,R_2S0vTjLelxcPVJJ,Romanos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Post-Master's Certificate,NaN,Not Selected
1,2018-05-08 06:51:04,2018-05-08 06:59:46,IP Address,147.140.233.17,100,522,True,2018-05-08 06:59:47,R_3OeRd0YvisWneHR,Caruso,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prelicensure BSN (Abington),NaN,Not Selected
2,2018-05-10 16:25:40,2018-05-10 16:36:37,IP Address,147.140.127.133,100,657,True,2018-05-10 16:36:37,R_3r1ceMys6CSAmRh,Clodfelter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Selected
3,2018-05-14 14:54:33,2018-05-14 14:58:26,IP Address,73.13.8.221,100,233,True,2018-05-14 14:58:27,R_3PUoYIdB8hIGslP,D'orazio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selected
4,2018-05-11 17:18:44,2018-05-11 17:24:38,IP Address,73.160.48.211,100,353,True,2018-05-11 17:24:38,R_R38OlWhckqRsvYJ,Nardone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Selected

In [10]:
dfs1.replace('TEMP','#NULL!')

,StartDate,EndDate,Status,IPAddress,Progress,Duration__in_seconds_,Finished,RecordedDate,ResponseId,RecipientLastTEMPme,...,JCHP2_4,JCHP3,OTD1,OTD2,OTD3,OTD4,OTD5,JCN1,JCN2,filter_$
0,2018-05-08 10:32:15,2018-05-08 10:51:19,IP Address,170.212.0.96,100,1143,True,2018-05-08 10:51:19,R_2S0vTjLelxcPVJJ,Romanos,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Post-Master's Certificate,#NULL!,Not Selected
1,2018-05-08 06:51:04,2018-05-08 06:59:46,IP Address,147.140.233.17,100,522,True,2018-05-08 06:59:47,R_3OeRd0YvisWneHR,Caruso,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Prelicensure BSN (Abington),#NULL!,Not Selected
2,2018-05-10 16:25:40,2018-05-10 16:36:37,IP Address,147.140.127.133,100,657,True,2018-05-10 16:36:37,R_3r1ceMys6CSAmRh,Clodfelter,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
3,2018-05-14 14:54:33,2018-05-14 14:58:26,IP Address,73.13.8.221,100,233,True,2018-05-14 14:58:27,R_3PUoYIdB8hIGslP,D'orazio,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
4,2018-05-11 17:18:44,2018-05-11 17:24:38,IP Address,73.160.48.211,100,353,True,2018-05-11 17:24:38,R_R38OlWhckqRsvYJ,TEMPrdone,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
5,2018-05-14 17:12:12,2018-05-14 17:15:23,IP Address,107.77.195.202,100,190,True,2018-05-14 17:15:23,R_r9gqMMxik3zUblf,Coccia,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,MSN,#NULL!,Not Selected
6,2018-05-14 13:10:24,2018-05-14 13:15:34,IP Address,107.77.195.157,100,310,True,2018-05-14 13:15:35,R_sp923skK8haS329,Wasserman,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
7,2018-04-27 17:36:29,2018-04-27 17:39:52,IP Address,68.81.70.45,93,202,False,2018-06-04 10:30:43,R_1eOTc5sWNGet2J6,Folk,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
8,2018-05-16 08:29:35,2018-05-16 08:34:41,IP Address,147.140.233.30,100,306,True,2018-05-16 08:34:42,R_2ATfyd05xjZMCwm,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
9,2018-05-11 14:12:23,2018-05-11 14:15:20,IP Address,73.112.80.245,100,177,True,2018-05-11 14:15:21,R_2QWDRgl3ZYqhCNe,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
10,2018-05-24 22:17:52,2018-05-24 22:22:23,IP Address,50.245.138.93,100,270,True,2018-05-24 22:22:24,R_29v8jpgZzpZmG78,McIntosh,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,FACT - 2 Year (Abington),#NULL!,Not Selected
11,2018-05-06 16:12:59,2018-05-06 16:19:13,IP Address,107.51.6.104,100,374,True,2018-05-06 16:19:14,R_3Rf6MAGiXkY7zWW,Hedin,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
12,2018-05-11 07:34:16,2018-05-11 14:16:55,IP Address,174.205.1.161,100,24159,True,2018-05-11 14:16:56,R_24xacdv39LGqMlk,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
13,2018-05-30 10:28:17,2018-05-30 10:30:54,IP Address,174.200.3.227,100,157,True,2018-05-30 10:30:55,R_3QWy7PGywGWxkaH,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
14,2018-05-04 16:20:56,2018-05-04 16:24:39,IP Address,100.11.92.225,100,222,True,2018-05-04 16:24:39,R_1cUtSoDillGwp3z,Hargy,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,DNP,I am currently taking mostly MSN courses.,Not Selected
15,2018-05-16 08:43:00,2018-05-16 08:53:01,IP Address,47.156.162.192,100,600,True,2018-05-16 08:53:01,R_216zy82yYZsEyJP,Trewin,...,#NULL!,Post-ProfessioTEMPl OTD,Yes,MS to OTD/Certificate,#NULL!,3-4 semesters including Spring 2018,Yes,#NULL!,#NULL!,Not Selected
16,2018-05-09 11:07:08,2018-05-09 11:08:12,IP Address,73.130.22.193,71,63,False,2018-06-04 10:30:42,R_Y5EFUytnIQ2AcG5,Barr,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,MSN,#NULL!,Not Selected
17,2018-04-28 07:05:23,2018-04-28 07:08:16,IP Address,73.233.88.241,100,173,True,2018-04-28 07:08:17,R_239SOCwdJNGgiGA,Mcguire,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
18,2018-05-04 18:08:39,2018-05-04 18:11:52,IP Address,104.220.108.97,100,192,True,2018-05-04 18:11:52,R_XAJ32PjYKt6Lk1b,Massa,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
19,2018-05-14 19:09:57,2018-05-14 19:16:30,IP Address,96.245.182.213,100,393,True,2018-05-14 19:16:31,R_3khREjEvMoieXNj,ZambraTEMP,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
20,2018-05-26 11:19:06,2018-05-26 11:21:46,IP Address,76.98.249.239,100,159,True,2018-05-26 11:21:47,R_tSWbGWAdGIDBMMV,Tieu,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Selected
21,2018-05-19 21:07:16,2018-05-19 21:11:23,IP Address,173.61.116.15,100,247,True,2018-05-19 21:11:23,R_1g1mugeEJf1IWW1,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
22,2018-05-14 16:38:21,2018-05-14 16:41:22,IP Address,68.83.166.82,100,181,True,2018-05-14 16:41:23,R_1mEGLjvFxwv4DKV,Gkonos,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
23,2018-05-14 15:47:21,2018-05-14 15:51:46,IP Address,98.225.177.60,100,265,True,2018-05-14 15:51:47,R_2thrEsgsrx80GWF,Harris,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,MSN,#NULL!,Not Selected
24,2018-05-05 07:02:31,2018-05-05 07:07:23,IP Address,73.226.28.217,100,292,True,2018-05-05 07:07:23,R_3GqOSIq5DsI19rO,Mclaughlin,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,FACT - 2 Year (Center City),#NULL!,Not Selected
25,2018-04-27 16:01:49,2018-04-27 16:29:39,IP Address,73.160.222.205,31,1670,False,2018-06-04 10:30:52,R_30ppwsdXFzg4JjR,Semple,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
26,2018-05-20 19:48:12,2018-05-20 19:51:11,IP Address,147.140.127.133,100,178,True,2018-05-20 19:51:11,R_1FG1qOLlCK3H5Ow,Kumar,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
27,2018-05-16 08:39:51,2018-05-28 08:18:28,IP Address,147.140.127.133,100,1035517,True,2018-05-28 08:18:29,R_3iJZTq0y0cfsA6T,O'neill,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
28,2018-04-28 10:23:43,2018-04-28 10:48:12,IP Address,72.237.206.161,100,1468,True,2018-04-28 10:48:12,R_3EWRzMefUdFrZK3,Shaw,...,#NULL!,Post-ProfessioTEMPl OTD,Yes,BS to OTD/Certificate,Matriculated student,3-4 semesters including Spring 2018,Yes,#NULL!,#NULL!,Not Selected
29,2018-04-28 09:42:12,2018-04-28 09:47:28,IP Address,71.225.65.219,100,316,True,2018-04-28 09:47:29,R_27xwW5UgGnIQmsJ,Depew,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,2018-05-30 07:57:20,2018-05-30 08:01:01,IP Address,109.177.180.61,100,220,True,2018-05-30 08:01:01,R_3KvI3TBoDDSxQGZ,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
333,2018-05-11 09:01:32,2018-05-11 09:14:17,IP Address,71.225.66.38,100,764,True,2018-05-11 09:14:18,R_1EgKjk0QQqAi0NX,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
334,2018-05-24 16:18:50,2018-05-24 16:25:01,IP Address,73.248.38.148,100,370,True,2018-05-24 16:25:01,R_29aI0hqsvllEZ5U,Donia,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
335,2018-04-28 10:59:30,2018-04-28 11:09:51,IP Address,174.225.20.180,100,621,True,2018-04-28 11:09:52,R_1PXZZVW1DPaBKW2,Mcewen,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
336,2018-05-24 16:01:32,2018-05-24 16:10:28,IP Address,69.249.204.192,100,535,True,2018-05-24 16:10:28,R_3snMl6CRXlCMYso,Nero,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
337,2018-05-05 06:25:38,2018-05-05 06:37:03,IP Address,71.224.245.97,100,684,True,2018-05-05 06:37:04,R_1DJ61tmsLip1oqf,Velez,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Prelicensure BSN (Abington),#NULL!,Not Selected
338,2018-05-14 14:17:29,2018-05-25 11:23:36,IP Address,47.133.136.204,100,939967,True,2018-05-25 11:23:37,R_UmfaOdfljXPfvX3,Duceman,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
339,2018-05-14 08:21:59,2018-05-14 08:25:16,IP Address,170.212.0.92,100,196,True,2018-05-14 08:25:16,R_1HqT8qfM1jSRKsL,Smith,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
340,2018-04-27 17:01:46,2018-04-27 17:16:57,IP Address,65.96.13.223,100,910,True,2018-04-27 17:16:57,R_3mgkiYzcxMFMR0a,Bao,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,MSN,#NULL!,Not Selected
341,2018-05-14 18:04:53,2018-05-14 18:07:17,IP Address,75.165.75.172,100,144,True,2018-05-14 18:07:17,R_V38ATI4NZWeAJih,Cordova-Martinez,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,MSN,#NULL!,Not Selected
342,2018-05-20 10:24:05,2018-05-20 10:28:03,IP Address,100.19.40.81,100,238,True,2018-05-20 10:28:04,R_3pbdcmNphUynjet,Sivori,...,#NULL!,Entry-Level OTD,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
343,2018-05-14 16:15:15,2018-05-14 16:42:58,IP Address,50.127.212.111,100,1662,True,2018-05-14 16:42:58,R_3m4qwb9ykI2kdoX,Blakely,...,#NULL!,Post-ProfessioTEMPl OTD,Yes,BS to OTD/Certificate,Matriculated student,5 or more semesters including Spring 2018,Yes,#NULL!,#NULL!,Not Selected
344,2018-04-27 22:17:31,2018-04-27 22:21:02,IP Address,198.54.81.16,100,211,True,2018-04-27 22:21:03,R_2S7co4VtWY9EyT9,Alcott,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Prelicensure BSN (Center City),#NULL!,Not Selected
345,2018-05-14 13:33:05,2018-05-25 14:22:56,IP Address,73.195.62.81,100,953391,True,2018-05-25 14:22:56,R_9v2dHSrLIAkKtgZ,Ahmad,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
346,2018-05-27 08:22:56,2018-05-27 08:28:01,IP Address,100.11.200.249,100,304,True,2018-05-27 08:28:01,R_2fqvp0gnZlSo2aZ,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
347,2018-05-02 11:04:07,2018-05-02 11:14:55,IP Address,147.140.127.133,100,648,True,2018-05-02 11:14:56,R_3CCrBDBSCMn1MjT,Tran,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
348,2018-04-30 07:54:23,2018-04-30 08:56:33,IP Address,67.98.222.31,63,3729,False,2018-06-04 10:30:44,R_3Ic6hXU4VJdLIl5,Lopez,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,FACT - 2 Year (Abington),#NULL!,Not Selected
349,2018-05-14 17:28:43,2018-05-14 17:33:58,IP Address,147.140.233.14,100,314,True,2018-05-14 17:33:58,R_1kHRfFDbdwpC7nu,GanTEMPmani,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
350,2018-05-06 09:55:52,2018-05-06 09:59:15,IP Address,76.98.235.191,100,202,True,2018-05-06 09:59:15,R_3FRoRLdwWPXMKzN,Nguyen,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
351,2018-05-15 12:04:39,2018-05-15 12:10:53,IP Address,73.165.65.168,100,374,True,2018-05-15 12:10:53,R_2t5u3mBhIvg9Qsl,Yakupova,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
352,2018-05-16 11:13:35,2018-05-16 11:35:49,IP Address,147.140.233.30,100,1333,True,2018-05-16 11:35:49,R_3n2aVaZKnJkoA1r,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
353,2018-05-08 10:18:06,2018-05-08 10:22:59,IP Address,174.200.26.205,100,293,True,2018-05-08 10:22:59,R_PLjG4HRkQAlhn33,Warner,...,#NULL!,Post-ProfessioTEMPl OTD,Yes,MS to OTD/Certificate,Matriculated student,5 or more semesters including Spring 2018,Yes,#NULL!,#NULL!,Not Selected
354,2018-05-28 18:16:41,2018-05-28 18:19:15,IP Address,71.185.54.199,100,153,True,2018-05-28 18:19:16,R_31hYlRz4epre08z,Rustin,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Prelicensure BSN (Abington),#NULL!,Not Selected
355,2018-05-04 16:31:38,2018-05-04 16:39:13,IP Address,99.203.20.38,100,454,True,2018-05-04 16:39:13,R_1Lu4XJMUmbhmajC,Shaw,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
356,2018-05-24 17:55:46,2018-05-24 17:58:41,IP Address,65.213.235.250,100,175,True,2018-05-24 17:58:42,R_3k5MKuwU4J9TDhA,Lai,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Selected
357,2018-05-16 14:31:09,2018-05-16 14:34:44,IP Address,73.141.79.73,100,214,True,2018-05-16 14:34:44,R_SHobdnuHLXLK5Vv,NaN,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,CRTEMP,#NULL!,Not Selected
358,2018-04-29 08:43:59,2018-04-29 08:49:36,IP Address,147.140.127.133,100,336,True,2018-04-29 08:49:37,R_qDRG3btg2yReaBz,Flaxenburg,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
359,2018-04-27 16:35:11,2018-04-27 16:41:15,IP Address,72.78.146.36,100,363,True,2018-04-27 16:41:16,R_3nugYEYrcT77eFf,Trump,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
360,2018-05-14 13:13:11,2018-05-14 13:15:08,IP Address,147.140.127.133,100,117,True,2018-05-14 13:15:09,R_1l4NKpJXCVVCCaR,Heinke,...,#NULL!,MSOT,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected
361,2018-05-01 08:47:26,2018-05-01 08:59:30,IP Address,73.197.57.230,100,724,True,2018-05-01 08:59:30,R_2QLCcCl0ycEojCg,Mayo,...,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,#NULL!,Not Selected

In [58]:
dfs = dfs['CL6']

In [59]:
dfs.tail()

357
358    Would appreciate if the library was cleaned mo...
359
360                                                  N/A
361
Name: CL6, dtype: object